# Site settings
title: Bridget & Steve
description: > # this means to ignore newlines until "baseurl:"
  Bridget and Steve got married!
baseurl: "/bridgetandsteve/" # the subpath of your site, e.g. /blog/
url: "http://bridgetandsteve.us" # the base hostname & protocol for your site

safe: true
host: 0.0.0.0

# Build settings
markdown: kramdown
